<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Platforms>x64</Platforms>
		<Configurations>Debug;Release;MixedPlatforms</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
		<PackageReference Include="Azure.AI.Vision.ImageAnalysis" Version="1.0.0" />
		<PackageReference Include="HttpMultipartParser" Version="10.0.0" />
		<PackageReference Include="Microsoft.Azure.CognitiveServices.Vision.ComputerVision" Version="7.0.1" />
		<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.59.0-preview.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.51.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.3.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" OutputItemType="Analyzer" />
		<PackageReference Include="Microsoft.ML" Version="5.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
		<PackageReference Include="PDFsharp-MigraDoc" Version="7.0.0-preview-1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ExpenseCategorizer.Shared\ExpenseCategorizer.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="host.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Fonts\Roboto-Regular.ttf">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Models\expenseModel.zip">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Fonts\" />
	  <Folder Include="Models\" />
	</ItemGroup>

	<!-- Prevent duplicate assembly attribute generation from WorkerExtensions auto-generated files under obj -->
	<ItemGroup>
	  <Compile Remove="obj\**\WorkerExtensions\**\*.AssemblyInfo.cs" />
	</ItemGroup>
</Project>
